===========================================-====
= RHCE / ANSIBLE                               =
= study notes    2023.03.21                    = 
================================================

Ch5. Configure Ansible Managed Nodes ===========================================
cat /etc/ansible/hosts   # create host with 3 slaves
[webservers]   
WebServer1
[dbserver]
DBServer1
[admins]
AdminServer1
ssh-copy-id ansible@WebServer1  # copy pub key to 3 slaves 
ansible ALL=(ALL) NOPASSWD: ALL    # add ansible root previlage for 3 slaves: 
ansible all -m ping # verify by ping 

Ch6. Scripting Administration Tasks with Ansible===============================
for i in webserver1 dbserver1 adminserver1;
   do ssh ansible@$i "sudo tar -czf messages.tar.gz /var/log/messages";
done
ansible -m fetch -a "src=/home/ansible/messages.tar.gz dest=/tmp/messages" all

Ch7. Core Component + variables =========================================
---
# variable.yml playbook content, run with: ansible-playbook variables.yml 
- name: Removes tcpdump from non-admin servers, install git on redhat servers
  hosts: all
  become: yes
  tasks:
   - name: rm tcpdump from all but admin server
     yum:
      name: tcpdump
      state: absent
     when: "'admin' not in inventory_hostname"
   - name: install git on redhat servers
     yum:
      name: git
      state: present
     when: ansible_facts['os_family'] == 'RedHat'

Ch7. Create Ansible Plays and Playbooks ======================
# 7.1  Commonly Used Modules
ansible -m ping all # 1. Verify Connectivity in the Environment
# 2.Install httpd
# 3. Start and Enable the httpd Service
# 6. Create /var/www/html/index.html
---
# Common Modules Playbook
#
- name: Common Modules Playbook
  become: yes
  hosts: webservers

  tasks:
   - name: Install httpd on webservers
     yum:
      name: httpd
      state: present
   - name: Start the httpd service
     service:
      name: httpd
      state: started
      enabled: yes
   - name: Create index.html
     file:
      path: /var/www/html/index.html
      state: touch
# 4. Create a dba User Account
# 5. Copy the Required File
---
- name: DB server playbook
  become: yes
  hosts: dbservers
  tasks:
   - name: Add the 'dba' user to the dbservers
     user:
       name: dba
   - name: Copy required DBA files
     copy:
      src: /root/DBAstuff.txt
      dest: /home/dba/
      owner: dba
      group: dba
      mode: 0600
# 7. Clone the Ansible Git Repository into /opt on adminservers
---
- name: Use git to clone the Ansible repo
  hosts: admins
  become: yes
  tasks:
   - name: Install git
     yum:
      name: git
      state: present
   - name: Use the git module
     git:
      repo: https://github.com/ansible/ansible.git
      dest: /opt

# 7.2 Complex Conditional 
Install the linuxacademy_backup_package, Accounting for the Repository or Package Not Being Available
Check for the Existence of /root/archive.tar and Create It If It Doesn't

---
#Conditional Playbook (ignore_errors)

- name: Conditional Playbook
  hosts: all
  become: yes

  tasks:
   - name: Install backup package
     yum:
      name: linuxacademy_backup_package
      state: present
     ignore_errors: true
   - name: Check for archive file
     command: ls /root/archive.tar
     register: check_result
     ignore_errors: true
   - name: Touch archive file
     file:
      path: /root/archive.tar
      state: touch
     when: check_result is failed

# 7.3 Get Clients to a Specific State
Install the "linuxacademy-backup-software" Package throughout Our Environment
Install httpd on the webserver Group
Start and Enable the httpd Service on the webserver Group
Create a dba User Account on the dbserver Group
Copy /root/DBAstuff.txt to the New User's Home Directory
Create index.html in /var/www/html on the Web Server
Install Git on the webserver and dbserver Groups, If It Is Not Already Installed
Create Red Hat Server-Specific Files
Running the Playbook
---
- name: Install backup software
  hosts: all
  become: yes
  tasks:
   - name:  yum command
     yum:
      name: linuxacademy-backup-software
      state: present
     ignore_errors: yes
- name: Install httpd
  hosts: webservers
  become: yes
  tasks:
   - name: httpd install
     yum:
      name: httpd
      state: present
   - name: Service management for httpd
     service:
      name: httpd
      state: started
      enabled: yes
- name: DB server management
  hosts: dbservers
  become: yes
  tasks:
   - name: Add user
     user:
      name: dba
      state: present
   - name: Copy DB user data
     copy:
      src: /root/DBAstuff.txt
      dest: /home/dba/DBAstuff.txt
      owner: dba
      group: dba
      mode: 0600
- name: Set up index.html on webservers
  hosts: webservers
  become: yes
  tasks:
   - name: Create and populate index.html
     lineinfile:
      path: /var/www/html/index.html
      line: Waiting for content.
      create: yes
      owner: apache
      group: apache
      mode: 0644
- name: Enable devs to easily populate content
  hosts: webservers:dbservers
  become: yes
  tasks:
   - name: Install git
     yum:
      name: git
      state: present
- name: Red Hat specific configuration
  hosts: all
  become: yes
  tasks:
   - name: Populate file with IP addresses
     lineinfile:
      path: /root/addresses
      line: "{{ ansible_facts['all_ipv4_addresses'] }}"
      create: yes
     when: ansible_facts['os_family'] == 'RedHat'

Ch8. Ansible Modules for System Administration Tasks ==========
# 8.1 Manage Security 
# Ensure Ports 80 and 22 Are Open on Webservers
# Ensure Ports 5432 and 22 Are Open on dbservers
# Enable SELinux on All Servers
---
- name: webserver firewall rules
  hosts: webservers
  become: yes

  tasks:
   - name: ssh firewall rules
     firewalld:
      permanent: yes
      state: enabled
      immediate: yes
      service: ssh

   - name: http firewall rules
     firewalld:
      permanent: yes
      state: enabled
      immediate: yes
      service: http

- name: Set up firewalls on dbservers
  hosts: dbservers
  become: yes

  tasks:
   - name: ssh firewall rules
     firewalld:
      permanent: yes
      state: enabled
      immediate: yes
      service: ssh

   - name: postgres rules
     firewalld:
      permanent: yes
      state: enabled
      immediate: yes
      service: postgresql

- name: SELinux
  hosts: all
  become: yes

  tasks:
   - name: Enable SELinux
     selinux:
      state: enforcing
      policy: targeted

# 8.2 Manage File Content 
# Deploy `index.html`
# Copy and Execute the `db deploy` (deploy.sh) Script 
# Redeploy `index.html`
---
- name: copy webapp
  hosts: webservers
  become: yes
  tasks:
   - name: install webapp
     copy:
      src: /root/index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: 0644

- name: copy db script
  hosts: dbservers
  become: yes
  tasks: 
   - name: copy deploy script
#    script: /root/deploy.sh
     copy:
      src: /root/deploy.sh
      dest: /opt/deploy.sh
      owner: root
      group: root
      mode: 0755
   - name: Execute the script 
      command: sh /opt/deploy.sh 
ansible-playbook filedeploy.yml
---
- name: copy webapp
 hosts: webservers
 become: yes
 tasks:
  - name: install webapp
    copy:
     src: /root/index2.html
     dest: /var/www/html/index.html
     owner: apache
     group: apache
     mode: 0644
Run the playbook again: ansible-playbook filedeploy.yml

# 8.3 Manage Users and Groups
  Ensure the 'backups' Group Exists with the Correct GID on All Servers
  Create the 'new_backup' User on All Servers with the Required Settings
  Create the New Group and Add the 'new_backup' User
---
- name: verify group exists
 hosts: all
 become: yes
 tasks:
  - group: 
     gid: 12310
     name: backups
     state: present
  - group:
     gid: 12311
     name: new_backups
     state: present
  - user:
     name: old_backup
     state: absent
  - user:
     name: new_backup
     uid: 12427
     shell: /bin/false
     password_lock: yes
     groups: backups, new_backups

# 8.4 Manage Services 
#  Start httpd on the Clients in the webserver Group
#  Start PostgreSQL on Clients in the dbservers and adminservers Groups
---
- name: Start httpd
  hosts: webservers
  become: yes
  tasks:
  - service:
     name: httpd
     state: started
     enabled: yes

- name: Start postgresql
  hosts: dbservers:admins
  become: yes
  tasks:
  - systemd: #  Because the services need to start asynchronously, we have to use the systemd module
     name: postgresql
     state: started
     no_block: yes

# 8.5 Manage FS
# lvg, lvol, filesystem, and mount
---
- name: Disks playbook
  hosts: dbservers
  become: yes
  tasks:
   - name: Create the Volume Group
     lvg:
      vg: RHCE
      pvs: /dev/xvdg
   - name: Create Logical Volume
     lvol:
      lv: AppDB2
      vg: RHCE
      size: 10G
      pvs: /dev/xvdg
      state: present
   - name: Format the disk
     filesystem:
      dev: /dev/RHCE/AppDB2
      fstype: xfs
   - name: Mount the disk
     mount:
      fstype: xfs
      src: /dev/RHCE/AppDB2
      state: mounted
      path: /mnt/appdb2
ansible-playbook disks.yml
ssh ansible@dbserver1
df -h

# 8.6 Manage Archiving 
# Unpack the /root/file.tar.gz Tarball into /opt on DBServer1
# Unpack the devstuff Tarball into /opt on dbserver1
# Compress and Copy /var/log/messages from dbserver1 to the Ansible Host
---
- name: Copy data dev stuff and inflate data and dev stuff
  hosts: dbservers
  become: yes
  tasks:
  - unarchive:
     src: /root/file.tar.gz
     dest: /opt/
 - unarchive:
     src: /tmp/devstuff.tar.gz
     dest: /opt/
     remote_src: yes
  - archive:
     path: /var/log/messages
     dest: /tmp/messages.tar.gz
  - fetch:
     src: /tmp/messages.tar.gz
     dest: /tmp/

# 8.7 Manage Scheduled Tasks  
# Write a Playbook to Create a Weekly YUM Update Job in Cron
# Write a Playbook to Execute /usr/bin/status on Reboot
# Write a Playbook to Execute /usr/bin/faillock_report at the Required Time
- name: Cron jobs
     hosts: all
     become: yes

     tasks:
     - cron:
        name: "Weekly YUM Update"
        special_time: weekly
        job: "/usr/bin/yum update -y"

     - cron:
        name: "Reboot Status"
        special_time: reboot
        job: "/usr/bin/status"

     - cron:
        name: "Faillock Report"
        job: /usr/bin/faillock_report
        weekday: "1,3,5"
        minute: "30"
        hour: "7"
        
Ch9. Using templates =====================================
# Write a Template to Replace the Document Root in httpd.conf and Any Other Configurations Required
# Write a Playbook to Deploy the Template to the webserver Group
Using the provided httpd.template, replace all occurrences of /var/www/ with {{ variable_name }}, e.g. DocumentRoot "{{ webdir }}html"

---
- name: Template playbook
  hosts: webservers
  become: yes
  vars:
   webdir: '/opt/'

  tasks:
   - name: Deploy the web template
     template:
      src: /root/httpd.template
      dest: /etc/httpd/conf/httpd.conf

ssh ansible@webserver1
ansible-playbook template.yml
sudo grep opt /etc/httpd/conf/httpd.conf

Ch10. Roles  =============================================
Ch11. Managing Parallelism ===============================
Ch12. Sensitive data / Vault =============================
# Write the Playbook to be Encrypted
# Encrypt the Playbook
# Run the Encrypted Playbook

---
- name: Deploy DBA password file
  hosts: dbservers
  become: yes

  tasks:
   - name: Create and pgapass file
     lineinfile:
      line: 'LinuxAcad'
      create: yes
      owner: dba
      group: dba
      mode: 0600
      path: /home/dba/.pgpass

ansible-vault encrypt dba-pass.yml  # encrypt yml file 
ansible-playbook --ask-vault-pass dba-pass.yml  # requires password

Ch13. Documentation ======================================
